# Generated by Django 5.0.3 on 2024-03-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_lon', models.FloatField()),
                ('coord_lat', models.FloatField()),
                ('weather_main', models.CharField(max_length=50)),
                ('weather_description', models.CharField(max_length=50)),
                ('temp', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('sea_level', models.FloatField(null=True)),
                ('grnd_level', models.FloatField(null=True)),
                ('visibility', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('wind_deg', models.FloatField()),
                ('wind_gust', models.FloatField()),
                ('clouds_all', models.FloatField()),
                ('rain_one_hr', models.FloatField(null=True)),
                ('rain_three_hr', models.FloatField(null=True)),
                ('snow_one_hr', models.FloatField(null=True)),
                ('snow_three_hr', models.FloatField(null=True)),
                ('date_time', models.BigIntegerField()),
                ('country', models.CharField(max_length=6)),
                ('sunrise', models.BigIntegerField()),
                ('sunset', models.BigIntegerField()),
                ('timezone', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('cod', models.IntegerField()),
            ],
        ),
    ]
